const assert=require('node:assert/strict');
const F=require('../dist/finance.js');
const base={amount:12000,payment:1000,duration:12,durationUnit:'months',rate:0,rateUnit:'years'};
const close=(a,b,tol=1e-6)=>assert(Math.abs(a-b)<=tol,`${a} != ${b}`);
let checks=0;
function verify(raw,target){const r=F.solve(raw,target);close(r.rows.at(-1).balance,0);close(r.rows.reduce((s,x)=>s+x.principal,0),r.totalPrincipal,.001);for(let i=0;i<r.solved.length;i++){const l=r.solved[i];let balance=l.p;for(let j=0;j<l.n;j++)balance=balance*(1+l.r)-r.rows[j].payments[i];close(balance,0,.001);assert(r.rows.slice(l.n).every(row=>row.payments[i]===0));assert(l.last>0&&l.last<=l.a+.01);}for(const row of r.rows){close(row.payment,row.interest+row.principal,.001);assert(row.balance>=0);}checks++;return r;}
let r=verify([base],'duration');assert.equal(r.months,12);close(r.total,12000);
r=verify([{...base,payment:1100}],'duration');assert.equal(r.months,11);close(r.rows.at(-1).payment,1000);
r=verify([{...base,payment:20000}],'duration');assert.equal(r.months,1);close(r.total,12000);
r=verify([{...base,amount:260000,payment:1500,rate:3.2}],'duration');assert(r.months>200&&r.months<300);assert(r.rows.at(-1).payment<1500);
r=verify([{...base,amount:260000,payment:260}],'duration');assert.equal(r.months,1000);
r=verify([{...base,payment:1}],'duration');assert.equal(r.months,12000);
verify([{...base,amount:10000,payment:900,rate:1,rateUnit:'months'}],'duration');
r=verify([base],'amount');close(r.totalPrincipal,12000);
r=verify([{...base,payment:1000,rate:12}],'amount');close(r.totalPrincipal,1000*(1-Math.pow(1.01,-12))/.01);
close(F.solve([{...base,payment:1000,rate:1,rateUnit:'months'}],'amount').totalPrincipal,r.totalPrincipal);
r=verify([base],'rate');close(r.solved[0].r,0);
const payment=100000/F.factor(.005,360);
r=verify([{...base,amount:100000,duration:30,durationUnit:'years',payment}],'rate');close(r.solved[0].r,.005,1e-12);
r=verify([{...base,amount:1000,duration:1,payment:1010}],'rate');close(r.solved[0].r,.01);
r=verify([{...base,amount:100000,duration:360,payment:599.55}],'rate');assert(r.solved[0].r>0.00499&&r.solved[0].r<.00501);
verify([base,{...base,amount:24000}],'duration');
verify([base,{...base,payment:1200}],'rate');
verify([base,{...base,payment:1200}],'amount');
assert.throws(()=>F.solve([{...base,rate:12,payment:120}],'duration'),/noPayoff/);
assert.throws(()=>F.solve([{...base,rate:12,payment:100}],'duration'),/noPayoff/);
assert.throws(()=>F.solve([{...base,payment:.5}],'duration'),/termLimit/);
assert.throws(()=>F.solve([{...base,payment:999}],'rate'),/noRate/);
for(const target of ['rate','duration','amount'])for(const payment of ['',0,-1,Infinity])assert.throws(()=>F.solve([{...base,payment}],target));
assert.throws(()=>F.solve([{...base,duration:1.5}],'amount'),/invalid/);
console.log(`PASS: ${checks} inverse schedules; known-rate recovery; 0% interest; partial final payment; annual/monthly equivalence; multi-loan, 1000/12000 months and impossible cases.`);
